name: my_pesa
version: 2.2.0+1
publish_to: none
description: Lets you View and Export MPESA Transactions
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  basic_utils: ^5.3.0
  bloc: ^8.1.2
  collection: ^1.17.1
  emoji_picker_flutter: ^1.6.1
  equatable: ^2.0.5
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_file_dialog: ^3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_sms_inbox:
    git:
      url: https://github.com/williamluke4/flutter_sms_inbox.git
      ref: master # branch name
  google_sign_in: ^6.1.4
  google_sign_in_dartio: ^0.2.2+1
  googleapis: ^11.2.0
  http: ^0.13.5
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  layout: ^1.0.3
  logger: ^2.0.0
  multi_select_flutter: ^4.1.3
  multiple_result: ^5.0.0
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.4.1
  provider: ^6.0.5
  sentry_flutter: ^7.8.0
  settings_ui: ^2.0.2
  sim_data_plus:
    git:
      url: https://github.com/williamluke4/sim_data_plus
      ref: main
  syncfusion_flutter_charts: ^22.1.36
  tab_container: ^2.0.0
  tuple: ^2.0.2
  url_launcher: ^6.1.11
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
