name: my_pesa
version: 2.0.5+1
publish_to: none
description: Lets you View MPESA Transactions
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  basic_utils: ^4.2.0
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_sms_inbox: ^1.0.1
  google_sign_in: ^5.3.0
  googleapis: ^8.1.0
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  logger: ^1.1.0
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  provider: ^6.0.2
  settings_ui: ^2.0.2

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
