name: my_pesa
version: 2.0.17+1
publish_to: none
description: Lets you View and Export MPESA Transactions
environment:
  sdk: ">=2.17.0 <2.20.0"
dependencies:
  basic_utils: ^5.3.0
  bloc: ^8.1.0
  collection: ^1.16.0
  emoji_picker_flutter: ^1.4.0
  equatable: ^2.0.5
  file_picker: ^5.2.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_file_dialog: ^2.3.2
  flutter_localizations:
    sdk: flutter
  flutter_sms_inbox: ^1.0.1
  google_sign_in: ^5.4.2
  google_sign_in_dartio: ^0.2.1
  googleapis: ^9.2.0
  http: ^0.13.5
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_serializable: ^6.4.0
  layout: ^1.0.3
  logger: ^1.1.0
  multiple_result: ^1.0.4
  path: ^1.8.2
  path_provider: ^2.0.11
  permission_handler: ^10.0.1
  provider: ^6.0.3
  sentry_flutter: ^6.11.0
  settings_ui: ^2.0.2
  syncfusion_flutter_charts: ^20.2.50
  tab_container: ^2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.1.5
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
