name: my_pesa
version: 2.0.13+1
publish_to: none
description: Lets you View and Export MPESA Transactions
environment:
  sdk: ">=2.17.0 <2.20.0"
dependencies:
  basic_utils: ^5.3.0
  bloc: ^8.1.0
  charts_flutter: ^0.12.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_sms_inbox: ^1.0.1
  flutter_swipe_action_cell: ^3.0.4
  google_sign_in: ^5.4.1
  google_sign_in_dartio: ^0.2.1
  googleapis: ^9.2.0
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_serializable: ^6.4.0
  logger: ^1.1.0
  multiple_result: ^1.0.4
  path_provider: ^2.0.11
  permission_handler: ^9.2.0
  provider: ^6.0.3
  sentry_flutter: ^6.9.1
  settings_ui: ^2.0.2
  url_launcher: ^6.1.5
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
