name: my_pesa

on: [pull_request, push]

jobs:
  test:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 2.10.0
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # or: 'beta' or 'master'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
      - run: flutter pub get
      - run: flutter test
      # Setup Keystore ANDROID_KEYSTORE=(openssl base64 -A -in my.keystore > base64)
      - run: echo -n ${ANDROID_KEYSTORE} | base64 -d > ./android/my.keystore
      - run: echo "keystorePath=./my.keystore" > ./android/key.properties
      - run: echo "keystorePassword=${KEYSTORE_PASSWORD}" >> ./android/key.properties
      - run: echo "keyAlias=${ALIAS_NAME}" >> ./android/key.properties
      - run: echo "keyPassword=${KEY_PASSWORD}" >> ./android/key.properties

      # Build
      - run: flutter build apk --flavor production -t ./lib/main_production.dart
      - run: flutter build appbundle  --flavor production -t ./lib/main_production.dart
